/**
 * Game-wide constant values
 */

export const WORLD = {
  SPAWN_SAFE_RADIUS: 200,
  DECORATION_COUNT: 50,
  BORDER_THICKNESS: 32
};

export const ENEMY = {
  DEFAULT_SPAWN_DISTANCE: 400,
  DEFAULT_ATTACK_RANGE: 50,
  DEFAULT_ATTACK_DAMAGE: 1,
  DEFAULT_ATTACK_COOLDOWN: 1000,
  DEFAULT_SPEED: 100,
  DEFAULT_PHASE_DURATION: 2000,
  DEFAULT_PHASE_INTERVAL: 5000,
  DEFAULT_EXPERIENCE: 1
};

export const PLAYER = {
  DEFAULT_SPEED: 100,
  DIAGONAL_MOVE_NORMALIZER: Math.sqrt(0.5)
};

export const UI = {
  HEALTH_BAR: {
    WIDTH: 200,
    HEIGHT: 20,
    PADDING: 10
  },
  EXPERIENCE_BAR: {
    WIDTH: 400,
    HEIGHT: 10,
    PADDING: 10
  }
}; 