name: Game CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        npm ci
        
    - name: Run Linter
      run: |
        npm run lint
        
    - name: Run Tests
      run: |
        npm test
        
    - name: Run Regression Prevention Tests
      run: |
        npm test src/tests/regressionPrevention.test.js
        
    - name: Upload Test Coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/
        
  build:
    needs: test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm ci
        
    - name: Build Game
      run: npm run build
      env:
        NODE_ENV: production
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: game-build
        path: dist/
        
  deploy-staging:
    needs: build
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: game-build
        path: dist/
        
    - name: Deploy to Staging
      run: |
        echo "Deploy to staging server would happen here"
        # Add your deployment commands here 